#!/bin/bash
# nicenumber -- 将定义的数字以逗号分隔的形式显示出来

nicenumber()
{
    integer=$(echo $1 | cut -d. -f1)    # 小数分隔符左侧
    decimal=$(echo $1 | cut -d. -f2)    # 小数分隔符右侧

    if [ "$decimal" != "$1" ] ; then
        result="${DD:='.'}$decimal"
    fi

    thousands=$integer

    while [ $thousands -gt 999 ] ; do
        remainder=$(($thousands % 1000))
        while [ ${#remainder} -lt 3 ] ; do
            remainder="0$remainder"
        done

        result="${TD:=","}${remainder}${result}"
        thousands=$(($thousands / 1000))
    done

    nicenum="${thousands}${result}"
    if [ !-z $2 ] ; then
        echo $nicenum
    fi
}

DD="."      # 小数分隔符，分隔整数部分和小数部分
TD=","      # 千位分隔符，隔3隔数字出现一次
